# Linear Algebra

## Transpose of a Matrix

Let A and B be matrices of appropriate sizes. The following hold:
1. $ (A^{T})^{T} = A $
2. $ (A + B)^{T} = A^{T} + B^{T} $
3. $ (αA)^{T} = αA^T $
4. $ (AB)^{T} = B^{T}A^T $

In [88]:
import numpy as np
import scipy

In [89]:
# Proof

A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

B = np.array([[6, 4, 9], [1, 4, 7], [3, 0, 6]])

# 1.
print(((A.T).T == A).all())

# 2.
print((((A + B).T == (A.T + B.T))).all())

# 3. 
print((((5 * A).T) == (5 * A.T)).all())

# 4. 
print( (((A * B).T) == (B.T * A.T)).all())

True
True
True
True


## Inverse of a Matrix

The inverse of a matrix is calculated as follows

$ A^{-1} = \frac{\large{1}}{\large{|A|}} Adj(A) $ 

where $ Adj(A) $ is the Adjoint matrix and is defined as $ Adj(A) = (cofactor(A))^{T} $  

A square matrix A is invertible if and only if $ |A| \neq 0 $

If the matrix A is invertible, then 

$ A A^{-1} = I  $

Let A and B be invertible matrices, the following identities hold:

1. $ (A^{−1})^{−1} = A $

2. $ (AB)^{−1} = B^{−1} A^{−1} $

3. $ (A^{T})^{−1} = (A^{−1})^{T} $

In [90]:
# setup

A = np.array([[0, -3, -2], [1, -4, -2], [-3, 4, 1]])

B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

A_inv = scipy.linalg.inv(A)

B_inv = scipy.linalg.inv(B)


# 1.
print((np.round(scipy.linalg.inv(A_inv), 4) == A).all())

# 2. 
print((np.round(scipy.linalg.inv(np.matmul(A, B)), 4) == np.round(np.matmul(B_inv, A_inv), 4)).all())

# 3. 
print((np.round(scipy.linalg.inv(A.T), 4) == np.round(scipy.linalg.inv(A).T, 4)).all())

True
True
True


## Determinant of a Matrix

1. Let A and B be square matrices, then
    
    <span style="color:gold"> |AB| = |A||B| </span>

2. If matrix A is invertible, then

    $ |A^{-1}| = \Large{\frac{1}{|A|}} $

3. Suppose that A is a square matrix and let B be the matrix obtained by interchanging two rows of A, then 

    $ |B| = −|A| $

4. If A is a square matrix with two rows (or two columns) that are equal then

    $ |A| = 0 $

5. Let A be a square matrix, and let B be the matrix obtained by multiplying a row of A by $ \beta $, then

    $ |B| = \beta|A| $

6. Let A be a square matrix, and let B be the matrix obtained from A by adding $ \beta $ times the kth row to the jth row, then 

    $ |B| = |A| $

7. Let A be a square matrix and let $ B = \beta A $, that is, B is obtained by multiplying every entry of A by $ \beta $, then 

    $ B = \beta^{n} |A| $
  

In [91]:
# numpy determinant
A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

print(scipy.linalg.det(A))

82.00000000000001


## Eigenvectors and Eigenvalues

1. Let A be an n × n matrix and let $ v $ be a non-zero vector. If the equation $ \boxed{\textbf{Av} = \lambda \textbf{v}} $ is true for some scalar $ \lambda $, then we call the vector $ v $ an eigenvector of A and we call the scalar $ \lambda $ an eigenvalue of A corresponding to $ v $.

2. Let A be an n × n matrix. The polynomial $ \boxed{p(\lambda) = |A − \lambda I|} $ is called the characteristic polynomial and is of nth degree.

3. If A is an n × n matrix and has n distinct eigenvalues $ \lambda_1, \lambda_2, . . . , \lambda_n $. Let $ v_i $ be an eigenvector of A corresponding to $ \lambda_{i} $. Then $ {v_1, v_2, . . . , v_n} $ is a basis for $ \mathbb{R}^{n} $.

4. The square matrix A is invertible if and only if $ \lambda = 0 $ is not an eigenvalue of A.

5. Let A be a triangular matrix (either upper or lower). Then the eigenvalues of A are its diagonal entries

6. If A is a symmetric matrix then all of its eigenvalues are real numbers

7. Let A be a symmetric matrix. If $ v_1 $ and $ v_2 $ are eigenvectors of A corresponding to distinct eigenvalues then $ v_1 $ and $ v_2 $ are orthogonal, that is, $ v_1 . v_2 = 0 $

In [92]:
A = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])

w, v= scipy.linalg.eig(A)

print('List of Eigenvalues', w)
print('\nList of Eigenvectors\n', v)

List of Eigenvalues [ 8.80916362+0.j  0.92620912+0.j -0.73537273+0.j]

List of Eigenvectors
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [93]:
# proof

eval_1 = 8.80916362
eval_2 = 0.92620912
eval_3 = -0.73537273

evec_1 = np.array([-0.52799324, -0.604391, -0.59660259])

print(A @ evec_1)
print(eval_1 * evec_1)

[-4.65117884 -5.32417919 -5.25556984]
[-4.65117884 -5.32417921 -5.25556983]


## Diagonalization

1. A matrix D whose off-diagonal entries are all zero is called a diagonal matrix.

2. A matrix A is called diagonalizable if it is similar to a diagonal matrix D, and there exists an invertible P such that
   
   <span style="color:gold"> A = PDP<sup>−1</sup></span>

3. A matrix A is diagonalizable if and only if there is a basis $ {v_1, v_2, . . . , v_n} $ of $ \mathbb{R}^{n} $ consisting of eigenvectors of A.

4. Suppose that A is a square matrix with n distinct eigenvalues $ λ_1, λ_2, . . . , λ_n $. Then A is diagonalizable.

5. A matrix A is diagonalizable if and only if the algebraic and geometric multiplicities of each eigenvalue are equal.

## Positive Definite / Semi-Definite

- A symmetric matrix A with real entries is positive-definite if the real number <span style="color:gold">z<sup>T</sup>Az</span> is positive for every nonzero real column vector z.

- A Hermitian matrix is positive-definite if the real number <span style="color:gold">z<sup>*</sup>Az</span> is positive for every nonzero complex column vector. 
  
  z<sup>*</sup> denotes the conjugate transpose of z.

- Positive semi-definite matrices are defined similarly, except that the scalars <span style="color:gold">z<sup>T</sup>Az</span> and <span style="color:gold">z<sup>*</sup>Az</span> are required to be positive or zero (that is, nonnegative). 
  
- Negative-definite and negative semi-definite matrices are defined analogously. A matrix that is not positive semi-definite and not negative semi-definite is sometimes called indefinite.

## Row Echeleon Form

A matrix is in row echelon form if:

- All zero rows are at the bottom.

- The first nonzero entry in a row (from the left) is located to the right of the first nonzero entry in every row above.

<img src="./images/lu_decomposition.png" style="filter:invert(1)" width="600px"/>



The three types of elementary row operations are:

- Interchange two rows.

- Multiply a row by a nonzero number.

- Add a multiple of a row to another row.

## PLU Decomposition

Let A be an m x n matrix. Then there exists a permutation matrix P such that <span style="color:gold">A = PLU</span>, where L is a lower triangular m x m matrix with 1s on the diagonal, U is an m x n upper triangular matrix and P is an m x m matrix known as the permutation matrix (a permutation of the rows of the identity matrix).



In [97]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

p, l, u = scipy.linalg.lu(A)

print(A)
print(u)
print(p)
print(p @ l @ u)

[[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]]
[[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[2. 5. 8. 7.]
 [5. 2. 2. 8.]
 [7. 5. 6. 6.]
 [5. 4. 4. 8.]]


## Cholesky Decomposition

Cholesky decomposition is a special case of LU decomposition applicable to Hermitian positive definite matrices.



## RU Decomposition



## LDL<sup>T</sup> Factorization

