# Linear Algebra

## Transpose of a Matrix

Let A and B be matrices of appropriate sizes. The following hold:
1. $ (A^{T})^{T} = A $
2. $ (A + B)^{T} = A^{T} + B^{T} $
3. $ (αA)^{T} = αA^T $
4. $ (AB)^{T} = B^{T}A^T $

In [49]:
import numpy as np

In [50]:
# Proof

A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

B = np.array([[6, 4, 9], [1, 4, 7], [3, 0, 6]])

# 1.
print(((A.T).T == A).all())

# 2.
print((((A + B).T == (A.T + B.T))).all())

# 3. 
print((((5 * A).T) == (5 * A.T)).all())

# 4. 
print( (((A * B).T) == (B.T * A.T)).all())

True
True
True
True


## Inverse of a Matrix

The inverse of a matrix is calculated as follows

$ A^{-1} = \frac{\large{1}}{\large{|A|}} Adj(A) $ 

where $ Adj(A) $ is the Adjoint matrix.

A square matrix A is invertible if and only if $ |A| \neq 0 $

If the matrix A is invertible, then 

$ A A^{-1} = I  $

Let A and B be invertible matrices, the following identities hold:

1. $ (A^{−1})^{−1} = A $

2. $ (AB)^{−1} = B^{−1} A^{−1} $

3. $ (A^{T})^{−1} = (A^{−1})^{T} $

In [51]:
# setup

A = np.array([[0, -3, -2], [1, -4, -2], [-3, 4, 1]])

B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

A_inv = np.linalg.inv(A)

B_inv = np.linalg.inv(B)


# 1.
print((np.round(np.linalg.inv(A_inv), 4) == A).all())

# 2. 
print((np.round(np.linalg.inv(np.matmul(A, B)), 4) == np.round(np.matmul(B_inv, A_inv), 4)).all())

# 3. 
print((np.round(np.linalg.inv(A.T), 4) == np.round(np.linalg.inv(A).T, 4)).all())

True
True
True


## Determinant of a Matrix

1. Let A and B be square matrices, then
    
    $ |AB| = |A||B| $

2. If matrix A is invertible, then

    $ |A^{-1}| = \Large{\frac{1}{|A|}} $

3. Suppose that A is a square matrix and let B be the matrix obtained by interchanging two rows of A, then 

    $ |B| = −|A| $

4. If A is a square matrix with two rows (or two columns) that are equal then

    $ |A| = 0 $

5. Let A be a square matrix, and let B be the matrix obtained by multiplying a row of A by $ \beta $, then

    $ |B| = \beta|A| $

6. Let A be a square matrix, and let B be the matrix obtained from A by adding $ \beta $ times the kth row to the jth row, then 

    $ |B| = |A| $

7. Let A be a square matrix and let $ B = \beta A $, that is, B is obtained by multiplying every entry of A by $ \beta $, then 

    $ B = \beta^{n} |A| $
  

In [52]:
# numpy determinant
A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

print(np.linalg.det(A))

82.00000000000001


## Eigenvectors and Eigenvalues

1. Let A be an n × n matrix and let $ v $ be a non-zero vector. If the equation $ \boxed{\textbf{Av} = \lambda \textbf{v}} $ is true for some scalar $ \lambda $, then we call the vector $ v $ an eigenvector of A and we call the scalar $ \lambda $ an eigenvalue of A corresponding to $ v $.

2. Let A be an n × n matrix. The polynomial $ \boxed{p(\lambda) = det(A − \lambda I)} $ is called the characteristic polynomial of A

3. If A is an n × n matrix and has n distinct eigenvalues $ \lambda_1, \lambda_2, . . . , \lambda_n $. Let $ v_i $ be an eigenvector of A corresponding to $ \lambda_{i} $. Then $ {v_1, v_2, . . . , v_n} $ is a basis for $ \mathbb{R}^{n} $.


In [53]:
A = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])

w, v= np.linalg.eig(A)

print('List of Eigenvalues', w)
print('\nList of Eigenvectors\n', v)

List of Eigenvalues [ 8.80916362  0.92620912 -0.73537273]

List of Eigenvectors
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [55]:
# proof

eval_1 = 8.80916362
eval_2 = 0.92620912
eval_3 = -0.73537273

evec_1 = np.array([-0.52799324, -0.604391, -0.59660259])

print(np.matmul(A, evec_1))
print(eval_1 * evec_1)

[-4.65117884 -5.32417919 -5.25556984]
[-4.65117884 -5.32417921 -5.25556983]
